name: sumbermaron
description: "Aplikasi booking tiket untuk pengunjung tempat wisata Sumber Maron."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  pretty_qr_code: ^2.0.3
  awesome_dialog: ^3.1.0
  webview_flutter: ^4.4.1
  cached_network_image: ^3.2.3

  intl: ^0.17.0
  http: ^1.0.0
  crypto: ^3.0.3
  url_launcher: ^6.1.14
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
